version: "3.8"
services:
    web:
        image: arrak/neighbor.server.finance:latest
        ports:
            - "5000:5000"
            - "5001:5001"
        container_name: "monthly-balance"
        networks:
            - neighbor
    database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        container_name: "db-monthly-balance"
        environment:
            - ACCEPT_EULA=Y 
            - SA_PASSWORD=vkiydKN6580!
            - MSSQL_PID=Express
        networks:
            - neighbor
networks:
    neighbor: