pipeline {
    agent any

    stages {
        stage('Code Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'GitHub', url: 'https://github.com/arrakya/Neighbor.Core.git']]])
            }
        }
        stage('Start Finance Database'){
            steps {
                script {
                    catchError {
                        sh 'docker container rm db-finance-sit --force'
                    }
                    sh 'docker-compose -f ./Neighbor.Server/docker-compose-sit.yml up -d db-finance'
                }
            }
        }
        stage('Build Finance Image') {
            steps {
                script {
                    sh 'docker build -f ./Neighbor.Server/Neighbor.Server.Finance/Dockerfile -t arrak/neighbor.server.finance:sit-latest . --build-arg EnvName=SIT --no-cache'
                }
            }
        }
        stage('Start Finance Service') {
            steps {
                script {
                     catchError {
                        sh 'docker container rm web-finance-sit --force'
                    }
                    sh 'docker-compose -f ./Neighbor.Server/docker-compose-sit.yml up -d web-finance'
                }
            }
        }
    }
}
