// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neighbor.Server.Finance.MonthlyBalance.Data;

namespace Neighbor.Server.Finance.Data.Migrations
{
    [DbContext(typeof(MonthlyBalanceDbContext))]
    [Migration("20210114065344_Add Monthly Balance table")]
    partial class AddMonthlyBalancetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Neighbor.Core.Domain.Models.Finance.MonthlyBalance", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<double>("ExpenseAmount")
                        .HasColumnType("float");

                    b.Property<double>("IncomeAmount")
                        .HasColumnType("float");

                    b.HasKey("Year", "MonthNo");

                    b.ToTable("MonthlyBalance", "Finance");

                    b.HasData(
                        new
                        {
                            Year = 2020,
                            MonthNo = 1,
                            ExpenseAmount = -188284.89999999999,
                            IncomeAmount = 1872340.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 2,
                            ExpenseAmount = -235860.82000000001,
                            IncomeAmount = 251070.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 3,
                            ExpenseAmount = -266707.34000000003,
                            IncomeAmount = 136430.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 4,
                            ExpenseAmount = -217859.64999999999,
                            IncomeAmount = 95760.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 5,
                            ExpenseAmount = -211140.29999999999,
                            IncomeAmount = 42390.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 6,
                            ExpenseAmount = -283869.91999999998,
                            IncomeAmount = 113990.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 7,
                            ExpenseAmount = -269949.78000000003,
                            IncomeAmount = 367770.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 8,
                            ExpenseAmount = -223690.06,
                            IncomeAmount = 123620.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 9,
                            ExpenseAmount = -267824.75,
                            IncomeAmount = 125480.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 10,
                            ExpenseAmount = 0.0,
                            IncomeAmount = 0.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 11,
                            ExpenseAmount = 0.0,
                            IncomeAmount = 0.0
                        },
                        new
                        {
                            Year = 2020,
                            MonthNo = 12,
                            ExpenseAmount = 0.0,
                            IncomeAmount = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
