// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neighbor.Server.Finance.MonthlyBalance.Data;

namespace Neighbor.Server.Finance.MonthlyBalance.Data.Migrations
{
    [DbContext(typeof(MonthlyBalanceDbContext))]
    partial class MonthlyBalanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Neighbor.Core.Domain.Models.Finance.MonthlyBalance", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("MonthNo")
                        .HasColumnType("int");

                    b.Property<double>("ExpenseAmount")
                        .HasColumnType("float");

                    b.Property<double>("IncomeAmount")
                        .HasColumnType("float");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Year", "MonthNo");

                    b.ToTable("MonthlyBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
