version: "3.8"
services:
    gateway:
        image: arrak/neighbor.server.api_gateway:prod-latest
        ports:            
            - "443:443"
        container_name: "gateway-prod"
        networks:
            - neighbor
    web-identity:
        image: arrak/neighbor.server.identity:latest
        container_name: "web-identity-prod"
        networks:
            - neighbor
    db-identity:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: "db-identity-prod"
        environment:
            - ACCEPT_EULA=Y 
            - SA_PASSWORD=vkiydKN6580!
            - MSSQL_PID=Express
        networks:
            - neighbor
    web-finance:
        image: arrak/neighbor.server.finance:prod-latest
        container_name: "web-finance-prod"
        networks:
            - neighbor
    db-finance:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: "db-finance-prod"
        environment:
            - ACCEPT_EULA=Y 
            - SA_PASSWORD=vkiydKN6580!
            - MSSQL_PID=Express
        networks:
            - neighbor
networks:
    neighbor:    
        name: neighbor