version: "3.8"
services:
    web:
        image: arrak/neighbor.server.api_gateway:latest
        ports:            
            - "80:80"
            - "8081:8081"
        container_name: "neighbor-api-gateway"
        networks:
            - neighbor
networks:
    neighbor:    
        name: neighbor