version: "3.8"
services:
    web:
        image: nginx:latest
        ports:
            - "8080:8080"
            - "80:80"
            - "8081:8081"
        container_name: "neighbor-api-gateway"
        volumes:
            - etc_nginx_confd/:/etc/nginx/conf.d
        networks:
            - neighbor
networks:
    neighbor:
volumes:
    etc_nginx_confd: