version: "3.8"
services:
    web:
        image: arrak/neighbor.server.identity:latest
        ports:
            - "6000:6000"
            - "6001:6001"
        container_name: "identity"
        networks:
            - neighbor
    database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1434:1433"
        container_name: "db-identity"
        environment:
            - ACCEPT_EULA=Y 
            - SA_PASSWORD=vkiydKN6580!
            - MSSQL_PID=Express
        networks:
            - neighbor
networks:
    neighbor: